wandb_version: 1

data_class:
  value: xarray_module.XarrayDataModule
dropout:
  value: 0.2
ft_schedule:
  value: hyperiap/litmodels/LitClassifier_ft_schedule_final.yaml
lr:
  value: 0.01
model_class:
  value: vit.simpleVIT
