name: CI testing

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  # Trigger the workflow on push or pull request, but only for the master branch
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  pytest:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 35

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test classifier
      run: |
        python run_classifier.py --limit_val_batches=5 --limit_train_batches=5 --max_epochs=2

    - name: Test self-supervised
      run: |
        python run_selfsupervised.py --limit_val_batches=5 --limit_train_batches=5 --max_epochs=2
        
    - name: Test run all
      run: |
        python run_all.py --ft_schedule=hyperiap/litmodels/LitClassifier_ft_schedule_final.yaml --limit_val_batches=5 --limit_train_batches=5 --max_epochs=2
        