name: smoke-tests

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  # Trigger the workflow on push or pull request, but only for the master branch
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  pytest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 35

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test 1-stage
      run: |
        python run_all.py --model_class=vit.simpleVIT --limit_val_batches=5 --limit_train_batches=10 --max_epochs=5

    - name: Test 2-stage
      run: |
        python run_all.py --model_class=vit.simpleVIT --limit_val_batches=5 --limit_train_batches=10 --max_epochs=5 --run_noisy --run_clean

    - name: Test 3-stage
      run: |
        python run_all.py --model_class=vit.simpleVIT --limit_val_batches=5 --limit_train_batches=10 --max_epochs=5 --run_ss --run_noisy --run_clean
